### PR TITLE
docs: Update just-the-docs theme to 0.5.3

### PR DESCRIPTION
**Pull request by travier**
Based on https://github.com/coreos/repo-templates/pull/145

### CODE REVIEW

**Comment by bgilbert** [comment]
LGTM pending #145.  I assume you've tested the docs sites with the new version?

**Comment by travier** [comment]
> I assume you've tested the docs sites with the new version?

Not yet but will do.

**Comment by travier** [comment]
Example at https://travier.github.io/afterburn/

**Comment by travier** [comment]
I've updated the example

**Review by bgilbert — APPROVED** [review]

**Pull request merged**
